### ISSUE TITLE
Sandbox mode?

### ISSUE THREAD

**Issue by oliver-xapix-io** [timdorr/model-s-api#14]
Hi Tim,

is there a sandbox mode? Who would I need to contact, so I get a demo dataset? I am trying to prepare sth for an upcoming hackathon, but buying a Tesla for that is a bit out of budget. ;)

Cheers, Oliver

**Comment by timdorr** [comment]
Unfortunately, no. Tesla doesn't provide anything like that, at least not to the public. You can either use [the gem's cassettes](https://github.com/timdorr/model-s-api/tree/master/spec/cassettes) or the return examples in [the online docs](http://docs.timdorr.apiary.io/). Apiary also attempts to create a mock server, but I'm not sure how accurate it is.
