### ISSUE TITLE
Should open_frunk have "front" for which_trunk?

### ISSUE THREAD

**Issue by walquis** [timdorr/model-s-api#17]
I notice that both open_frunk and open_trunk have which_trunk: "rear".

**Comment by timdorr** [comment]
Yes that is true. Although the endpoint is non functional, so it really doesn't matter yet :smile:

**Comment by walquis** [comment]
Cool.  Thanks for publishing your API wrapper!

**Comment by jonasman** [comment]
So what is the command `open_trunk`?
and `front `and `rear` as options?
