### ISSUE TITLE
Charge state has non valid json in examples

### ISSUE THREAD

**Issue by jonasman** [timdorr/model-s-api#20]
In charge state there is an example with non valid json:
```js
{
  "response": {

    "charging_state": "Complete",  // "Charging", ??
    "charge_to_max_range": false,  // current std/max-range setting
    "max_range_charge_counter": 0,
    "fast_charger_present": false, // connected to Supercharger?
    "battery_range": 239.02,       // rated miles
    "est_battery_range": 155.79,   // range estimated from recent driving
    "ideal_battery_range": 275.09, // ideal miles
    "battery_level": 91,           // integer charge percentage
    "battery_current": -0.6,       // current flowing into battery
    "charge_starting_range": null,
    "charge_starting_soc": null,
    "charger_voltage": 0,          // only has value while charging
    "charger_pilot_current": 40,   // max current allowed by charger & adapter
    "charger_actual_current": 0,   // current actually being drawn
    "charger_power": 0,            // kW (rounded down) of charger
    "time_to_full_charge": null,   // valid only while charging
    "charge_rate": -1.0,           // float mi/hr charging or -1 if not charging
    "charge_port_door_open": true
  }
}
```
Should I fork and fix it?

**Comment by dewski** [comment]
Are you referring to the comments?

**Comment by jonasman** [comment]
yes. It won't parse.

**Comment by timdorr** [comment]
Those are comments to make the result easier to read. Those obviously won't come through via the production API.

**Comment by jonasman** [comment]
They come in the mock server api, making testing impossible.

**Comment by timdorr** [comment]
The Apiary mock server isn't suitable for testing for a variety of reasons.

**Comment by jonasman** [comment]
I know. But i have no car :) and that was the best mock i found for testing my library

**Comment by dewski** [comment]
> I know. But i have no car :) and that was the best mock i found for testing my library

You could strip any comments before parsing the JSON.

**Comment by jonasman** [comment]
yes. That will need to be! My libraries don't do manual parsing. I use almost request to objects. 
In case you are interested: https://github.com/jonasman/TeslaSwift/blob/master/Sources/TeslaSwift.swift
