### ISSUE TITLE
Valet mode is incomplete

### ISSUE THREAD

**Issue by jonasman** [timdorr/model-s-api#25]
http://docs.timdorr.apiary.io/#reference/vehicle-commands/set-valet-mode/set-valet-mode

The valet mode API makes references to 3 parameters but the URI only shows 1.
Can you update it? I don't have a car to test :)

**Comment by timdorr** [comment]
The parameters go in the POST body, just like every other command.

**Comment by jonasman** [comment]
This one https://owner-api.teslamotors.com/api/1/vehicles/vehicle_id/command/set_charge_limit?percent=limit_value goes on the GET part, is this incorrect?

**Comment by timdorr** [comment]
That is also correct. It's possible to have params in both the body and the query string.
