### ISSUE TITLE
API lacking documentation of errors: requesting climate settings frequently returns HTML

### ISSUE THREAD

**Issue by artiestie** [timdorr/model-s-api#33]
Requesting get to https://owner-api.teslamotors.com/api/1/vehicles/"vehicleID"/data_request/climate_state with correct access header sometimes returns HTML instead of JSON, which seems like without explanation.

Also, some requests to charge also give me a 'Unable to connect to...' error.  Maybe these errors should be documented?

**Comment by artiestie** [comment]
Now thinking of it, they are possibly due to not waking up the vehicle beforehand.  Here's what I've gathered:

* Get status requests:

  * Climate settings returns HTML if car is not awake

  * All other requests return error:'Unable to connect to IP'

**Comment by timdorr** [comment]
There should be an error code on the HTTP response. I would check that before parsing the body.

**Comment by artiestie** [comment]
thanks, i was not waking the vehicle actually.  I did try parsing the body, but found the problem once I couldn't reproduce the issue :sparkles:
