### ISSUE TITLE
Getting 404 error testing basic Authentication call on http://docs.timdorr.apiary.io

### ISSUE THREAD

**Issue by kennethchapman99** [timdorr/model-s-api#34]
Not sure if this is appropriate place to post this issue - apologies if not..

I am using:
http://docs.timdorr.apiary.io/#reference/vehicle-commands/open-trunkfrunk/get-an-access-token?console=1

Passing in the grant_type, client_id, client_secret and my valid Tesla email and password (in plain text -- is that the issue?) --- and when I run that on 'Production' and choose 'Call Resource' - I always get a 404 error.... 

I can't figure out what I'm doing wrong, but suspect that this call should work.  NOOb :|

**Comment by timdorr** [comment]
Don't use the tools on the site. You need to make these requests in your language/library of choice.
