### ISSUE TITLE
Can't log in using owner-api URL

### ISSUE THREAD

**Issue by KonradIT** [timdorr/model-s-api#38]
The URL "https://owner-api.teslamotors.com/oauth/token" for getting an access_token is returning 404, I double checked the URL parameters. Nothing so far.

using "curl --request POST" the response is

    {"response":"undefined_method_`strip'_for_nil:nilclass"}

**Comment by timdorr** [comment]
It's not a query parameter. You need to out it in the post body. 

BTW, it's a little funny that their Ruby code is leaking :)

**Comment by KonradIT** [comment]
Gotcha. Thanks!
