### ISSUE TITLE
Can the charging rate be set via the API?

### ISSUE THREAD

**Issue by jamietownsend** [timdorr/model-s-api#44]
I'd like to be able to scale down the current drawn while charging if my solar panels are generating much power. I could easily just switch the charging off, but I'd like to be able to make the most out of what is being produced. Do you know of such an API or where else I could ask?

**Comment by hergaty** [comment]
+1

**Comment by timdorr** [comment]
Nope, the most you can do is stop and start charging, along with setting the charge limit. I haven't seen anything in my reverse engineering that allows for setting the rate remotely.
