### ISSUE TITLE
client_id and client_secret are likely out of date

### ISSUE THREAD

**Issue by HudsonGraeme** [timdorr/model-s-api#45]
Yesterday, using Swift to make a mac application with the API, everything was fine and i could login normally, but today, i keep getting this response from the server, even though my username and password are correct. 
`Status = "401 Unauthorized";
    "Www-Authenticate" = "Bearer realm=\"Doorkeeper\", error=\"\", error_description=\"translation missing: en.doorkeeper.errors.messages\"";`

I've checked for errors in the code, but it's fine as far as i can tell..

`<NSHTTPURLResponse: 0x618000026a80> { URL: https://owner-api.teslamotors.com/oauth/token?grant_type=password&client_id=e4a9949fcfa04068f59abb5a658f2bac0a3428e4652315490b659d5ab3f35a9e&client_secret=c75f14bbadc8bee3a7594412c31416f8300256d7668ea7e6e7f06727bfb9d220&username=********@*****.***&password=**************** } `

I also cannot access the access_token with the Apiary page, so my thoughts are that the client id and secret have been updated. 

Thanks!

**Comment by jonasman** [comment]
Works here

Sent from my iPhone

On 10 Jan 2017, at 01:57, HudsonGraeme <notifications@github.com<mailto:notifications@github.com>> wrote:


Yesterday, using Swift to make a mac application with the API, everything was fine and i could login normally, but today, i keep getting this response from the server, even though my username and password are correct.
Status = "401 Unauthorized"; "Www-Authenticate" = "Bearer realm=\"Doorkeeper\", error=\"\", error_description=\"translation missing: en.doorkeeper.errors.messages\"";

I've checked for errors in the code, but it's fine as far as i can tell..

<NSHTTPURLResponse: 0x618000026a80> { URL: https://owner-api.teslamotors.com/oauth/token?grant_type=password&client_id=e4a9949fcfa04068f59abb5a658f2bac0a3428e4652315490b659d5ab3f35a9e&client_secret=c75f14bbadc8bee3a7594412c31416f8300256d7668ea7e6e7f06727bfb9d220&username=********@*****.***&password=**************** }

I also cannot access the access_token with the Apiary page, so my thoughts are that the client id and secret have been updated.

Thanks!

-

**Comment by jamietownsend** [comment]
Works here too

**Comment by timdorr** [comment]
Make sure you're POSTing to the endpoint. It looks like you've got a GET request there, which won't work. Also, obviously make sure you've got the right password (it's happened to me!)

**Comment by HudsonGraeme** [comment]
Thanks! Glad it's just on my end.
Will look over code once again.
I do run into
`["response": undefined_method_`strip'_for_nil:nilclass]`
while debugging, but generally think nothing of it, as it returned the error a couple of days ago while it was working.
