### ISSUE TITLE
Streaming API

### ISSUE THREAD

**Issue by jonasman** [timdorr/model-s-api#50]
Recently i was trying to implement the streaming API on my swift lib but i noticed that Tesla is not using websockets anymore. 

Request

```
GET /stream/VEHICLE_ID/?values=speed,odometer,soc,elevation,est_heading,est_lat,est_lng,power,shift_state,range,est_range,heading HTTP/1.1
Connection: Upgrade
Host: streaming.vn.teslamotors.com
Origin: wss://streaming.vn.teslamotors.com/stream/VEHICLE_ID/?values=speed,odometer,soc,elevation,est_heading,est_lat,est_lng,power,shift_state,range,est_range,heading
User-Agent: SwiftWebSocket
Upgrade: websocket
Sec-WebSocket-Version: 13
Authorization: Basic !REMOVED!
Sec-WebSocket-Key: 6Dc+wQBQoGacYAPXzGctvg==
```

Response
```
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 23 Apr 2017 13:19:38 GMT
Content-Type: text/event-stream
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache
```

This seems to be HTTP SSE traffic. https://en.wikipedia.org/wiki/Server-sent_events

I implemented this into the lib but no data came from the stream. 

Streaming URL:
`https://streaming.vn.teslamotors.com/stream/VEHICLE_ID/?values=speed,odometer,soc,elevation,est_heading,est_lat,est_lng,power,shift_state,range,est_range,heading`

Can anyone here validate that this is in fact HTTP SSE and if so that your car produces events?

**Comment by jonasman** [comment]
I managed to fix my issue. The accept header of my request was incorrect. It must be `*/*`
To help ppl debug i found this command very usefull: 

`curl --user USERNAME:TOKEN https://streaming.vn.teslamotors.com/stream/VEHICLE_ID/?values=speed,odometer,soc,elevation,est_heading,est_lat,est_lng,power,shift_state`
from TMC: https://teslamotorsclub.com/tmc/threads/model-s-rest-api.13410/page-5

**Comment by bahree** [comment]
I tried this and I get the following error with that cURL. I heard that the streaming endpoint isn't supported in the Model 3 (Which is what I have), is that related to that or something else. Any ideas? And I can confirm the vehicle ID is correct. Thanks.

Got HTTP status: 404 Not Found for . Response: {"error":"vehicle not found (404)"}

**Comment by flexgames** [comment]
@bahree check out this post:
https://github.com/timdorr/model-s-api/issues/68#issuecomment-401522357

Can get lat/long but not much more. And it doesn't stream. Has to be polled. Ping me for more info.
