### ISSUE TITLE
404 Errors

### ISSUE THREAD

**Issue by allante2** [timdorr/model-s-api#51]
I am able to get an access token and my vehicle id, but all other calls result in 404 errors.  I have used both the "vehicle_id" and "id" codes, to no avail.  I have a 2016 Model X with the latest firmware build.  Is there something specific to a Model X that prevents compatibility with this API?  I would appreciate any assistance anyone can offer!

Here is an example of an error I received when trying to retrieve the car's charge state:

Response
404 

Headers
•	connection:keep-alive
•	server:nginx
•	date:Thu, 15 Jun 2017 16:58:43 GMT
•	content-type:application/json; charset=utf-8
•	content-length:60
•	status:404 Not Found
•	x-frame-options:SAMEORIGIN
•	x-xss-protection:1; mode=block
•	x-content-type-options:nosniff
•	cache-control:no-cache
•	x-request-id:c5561f18-e1cc-470d-99ab-4ddfa4598ad3
•	x-runtime:0.009613
•	x-newrelic-app-data:PxQDVFVRCQITVlZRDgcFV0YdFGQHBDcQUQxLA1tMXV1dSnwZQRNWERdcRE42LGtnH0tLQBsBGVZUAxoDTFNXVgZRDFMKAQQCA1UJUQBNEVRUFBtDAlYIVVMBWFQFBwRSAgkUHwQHDxFVPw==
•	via:1.1 vegur
Body
{
  "response": null,
  "error": "not_found",
  "error_description": ""
}

**Comment by timdorr** [comment]
You probably have the wrong URL. What URL are you attempting to access?

**Comment by allante2** [comment]
I am using http://docs.timdorr.apiary.io/#, which is captioned "Tesla Model S JSON API."  Does a different URL exist for the Model X?  I am able to get tokens and my vehicle id, however.

**Comment by timdorr** [comment]
That isn't the correct URL at all. They should be under `https://owner-api.teslamotors.com/api/1/`

**Comment by allante2** [comment]
Sorry for the confusion Tim, yes, that is the URL I am using.  So for charge stage, I am using https://owner-api.teslamotors.com/api/1/vehicles/vehicle_id/data_request/charge_state.

**Comment by timdorr** [comment]
It should definitely be the `id` field: https://github.com/timdorr/model-s-api/blob/master/lib/tesla_api/vehicle.rb#L147 Make sure you're also including the correct Authorization header. That's all I can think of.

**Comment by allante2** [comment]
Thanks.  I have used both the Id and vehicle_id codes, but both result in 404s.  I know that my token works, because I used that in my auth header to get the vehicle id codes.  Can't figure out why all of the calls fail.

**Comment by arrayaddu** [comment]
@allante2 Have you got  API working on production mode, i am getting the same error
