### ISSUE TITLE
Model 3 APIs

### ISSUE THREAD

**Issue by timdorr** [timdorr/model-s-api#52]
Model 3 support just landed in the apps. I haven't done any poking around, but perhaps some new stuff was added? If someone else wants to beat me to it, go right ahead!

**Comment by JeanPierreFig** [comment]
Does the model s api work with the model 3 ?

**Comment by bhusang** [comment]
Yes, I am able to use the same API calls and get similar data returned. I should note that I use just a few of the API calls (to get charging state, odometer, etc).

**Comment by rlabancz** [comment]
I am trying to use the API for my Model 3. Getting vehicle works, but charge_state / climate_state return a 404

**Comment by timdorr** [comment]
That's normal. Make sure you're referencing the right ID. There are two (one for the Rails APIs database record and one for the GUID of the car).

**Comment by flmueller** [comment]
Hi Tim, thanks for the API hacking! Do the OWNERAPI_CLIENT_ID/SECRET change regularly? How long does it take to get the new values when they have changed? 
Would you use the API for a commercial tool ? Is it reliable enough? Thanks a lot!

**Comment by mohamedmansour** [comment]
The homelink API is not working on Model 3, anyone could get it working? The other APIs seem working.

**Comment by timdorr** [comment]
The Model 3 doesn't yet have Summon/AutoPark, so it doesn't have the infrastructure necessary to operate HomeLink.

**Comment by mohamedmansour** [comment]
@timdorr I used homelink on my Model 3 to open and close the garage, when I tap that button it toggles the garage. When I use the HomeLink API right now, it gives me 400 error. So if I understand you correctly, even though my Model3 has HomeLink there is no infrastructure to open it remotely :'( I guess I have to call the lock smith.

**Comment by mikedicarlo** [comment]
I can get an access token and pull my vehicle data from the list vehicles endpoint (https://owner-api.teslamotors.com/api/1/vehicles). None of the state or vehicle command endpoints seem to work for the model 3.

**Comment by timdorr** [comment]
@mikedicarlo See #32

**Comment by mikedicarlo** [comment]
@timdorr thanks, that worked.

**Comment by tpozzy** [comment]
Tim,

I have a Model 3 and I'm interesting in working on the API. Is anyone else collaborating on this project for Model 3 development?

**Comment by mohamedmansour** [comment]
The API does work for model 3, the only endpoint which doesn’t is the homelink.

**Comment by bahree** [comment]
And streaming. Haven't checked the homelink one yet.

**Comment by timdorr** [comment]
Closing this out, since the 3 appears to have the same API surface as the S/X for now. But there are a bunch of new APIs for v9 to document...
