### ISSUE TITLE
Vehicle state APIs not working on production mode

### ISSUE THREAD

**Issue by array-addu** [timdorr/model-s-api#53]
I am not able to get the response from Vehicle State APIs, i am getting this error -
`{
  "response": null,
  "error": "not_found",
  "error_description": ""
}`
However Token and Vehicle details APIs are working fine. I am using this API

>  https://owner-api.teslamotors.com/api/1

**Comment by timdorr** [comment]
It sounds like you're not passing the right vehicle ID. Make sure you're using the `id` value for the vehicle, not `vehicle_id`. 

Also, a lot more information is needed. What exact URL are you hitting and what do the request headers look like?

**Comment by array-addu** [comment]
I am using this API

> https://owner-api.teslamotors.com/api/1/vehicles/my_vehicle_id/data_request/charge_state
With token as -

>  Authentication Bearer {access_token}
I am getting access token and vehicle details correct but any other API is not working, however they are working a while ago. Can you please confirm if they are running at your end ?

**Comment by timdorr** [comment]
You can look through the cassette files of the ruby gem in this repo to get the specifics: https://github.com/timdorr/model-s-api/blob/master/spec/cassettes/vehicle-charge_state.yml

Again, make sure you're using `id` from the vehicles endpoint, _not_ `vehicle_id`.

**Comment by array-addu** [comment]
I have checked both `id` and `vehicle_id` but both of them giving same 404 error. I went through the cassette file. Can you please verify if they are working currently ?

**Comment by timdorr** [comment]
Yup, otherwise the app wouldn't work :)

**Comment by array-addu** [comment]
I got it working by using `id_s`. The documentation shows` vehicle_id`, which is confusing and needs to be corrected.

**Comment by ramonsmits** [comment]
FYI: For those getting `not_found`, it seems Tesla changed the vehicle ID's. I hardcoded my ID and I'm now getting a different ID back.

**Comment by GaPhi** [comment]
Find your vehicleId from its VIN. It is more robust (the VIN will never
change, vehicleId is an internal database key which should not change but
may change/has changed)

Le jeu. 24 févr. 2022 à 09:25, Ramon Smits ***@***.***> a
écrit :
