### ISSUE TITLE
set_temps can only max cool

### ISSUE THREAD

**Issue by sepstrup** [timdorr/model-s-api#54]
I am trying to use the set_temps method, but it seems like it can only activate max cool and is ignoring the parameters.

Can anyone confirm or disprove this?

**Comment by timdorr** [comment]
Are you using temperatures in celsius?

**Comment by sepstrup** [comment]
Yes, tried lots of different values. It is supposed to be an int or double right?

**Comment by sepstrup** [comment]
Tried http://docs.timdorr.apiary.io/#reference/vehicle-commands/set-temperature/set-temperature?console=1 as well...

**Comment by sepstrup** [comment]
I have been testing a bit more... Can only set it to max cool... I think some parameters might have changed...

**Comment by sepstrup** [comment]
Ok this lib is working - this http://docs.timdorr.apiary.io/#reference/vehicle-commands/set-temperature/set-temperature?console=1 doc it outdated :-)

**Comment by timdorr** [comment]
Yeah, that's not exactly clear. It should be more readable now.

**Comment by bharned3** [comment]
Working on n app: I know this is closed but facing similar issue and can't see what I am missing. When I post temperature it always just defaults to low. My gui data shows Fahrenheit but it always returns celsius.  When I adjust temp in my app it resets to LO on the car.

**Comment by ChadMoran** [comment]
Regardless of UI settings the temp API works in C.

**Comment by timdorr** [comment]
By the way, that's C as in "celsius", not the programming language 😉

**Comment by ChadMoran** [comment]
Hah, yes it is. 👍 Thanks for clarifying.

**Comment by bharned3** [comment]
So I need to convert back to Celsius when sending back to car I assume. I’ll play around some more. Thanks

**Comment by bharned3** [comment]
Ugh still stuck on this. Here is what I am passing and it always just sets the temps to LO

https://owner-api.teslamotors.com/api/1/vehicles/vehicle_id/command/set_temps?driver_temp=driver_temp&passenger_temp=passenger_temp

where vehicle_id is my vehicle_id
where driver_temp ( i tried 26 and 26.0) just hard codes while debugging
where passenger_temp ( i tried 26 and 26.0) just hard codes while debugging

passing in my token in the header and null to the body.

If it matters I am using the Ionic framework

**Comment by dacastro4** [comment]
@bharned3 I'm having the same issue.

**Comment by dacastro4** [comment]
If someone has the same problem, send the same parameters but in the body. i.e:

`{"driver_temp": "22.8", "passenger_temp": "23.1"}`

**Comment by chrispi68** [comment]
Same problem for me, even if I put the parameters in the body.

Why is this issue closed?

**Comment by klacol** [comment]
confirming @dacastro4 , we found out, that these params must be in the body, then it works.

**Comment by gohnjanotis** [comment]
In my case I also had to make sure I was explicitly setting the `Content-Type` header to `application/json` — it didn't work until I did that, even though I was putting it in the body of the POST request.

**Comment by SylvainGa** [comment]
Can't get it to work either. As specified in the doc, it sets to MIN. As mentioned here, nothing happens. Here's my code:

```
    function climateSet(vehicle, notify, temperature) {
        var driver_temp = temperature;
        var url = "https://owner-api.teslamotors.com/api/1/vehicles/" + vehicle.toString() + "/command/set_temps?driver_temp=" + driver_temp.toString() + "&passenger_temp=" + driver_temp.toString();
        Communications.makeWebRequest(
            url,
            {
                "driver_temp=" => driver_temp.toString(),
                "passenger_temp=" => driver_temp.toString()
            },
            {
                :method => Communications.HTTP_REQUEST_METHOD_POST,
                :headers => {
                    "Authorization" => _token,
                    "Content-Type" => "application/json"
                },
                :responseType => Communications.HTTP_RESPONSE_CONTENT_TYPE_JSON
            },
            notify
        );
    }

```

I'm stuck. Anybody care to help? Thanks.
