### ISSUE TITLE
API support for changing charge rate (in amps)

### ISSUE THREAD

**Issue by vloschiavo** [timdorr/model-s-api#57]
Hello,

Would it be possible to add support for changing the charge rate?  I'd like to use my surplus power from solar to send it to the grid.  Via the [Tesla Powerwall API](https://forums.tesla.com/forum/forums/rest-interface-powerwall-2-energy-gateway) I can see how much power is going to the grid.  I'd like to vary the charge rate of the car to match the excess power going to the grid.  

I would need someone to sniff the API call from the phone application to capture the POST message and document.

Thank you,
-Vince

**Comment by timdorr** [comment]
This is up to Tesla. We don't control their API, just document it.

**Comment by ChadMoran** [comment]
To expand on what @timdorr said.  Telsa doesn't currently support changing the charging rate in the app for cars.  Unless this feature becomes available when you have a powerwall, which I'm not aware of.

So if it does exist someone could snoop the traffic.  Otherwise, there's nothing that can be done.

**Comment by frizull** [comment]
You might not have to wait much longer, though. Seems that wish made it to the top: https://twitter.com/elonmusk/status/932649922666438656

**Comment by lewurm** [comment]
Did anyone have success finding some hidden API?

There was a firmware update for Powerwall that suggest some kind of API for controlling the charge rate in the cars was added: https://www.teslarati.com/tesla-powerwall-vehicle-charging/ However I guess Tesla has different means to talk to the cars 😕
