### ISSUE TITLE
Is there a way to get the battery size?

### ISSUE THREAD

**Issue by FrancoSabadini** [timdorr/model-s-api#58]
I was wondering if there is a way to get the car's battery size? I saw that there is a `battery_range` parameter in the response of the `charge_state` request (which I assume is the range for the fully charged battery) but it seems like a strange place to put the battery size, which is a static value that should be returned with the car information. Is this parameter referring to something else maybe?

Thanks in advance for the response and for the great work documenting these APIs!!

**Comment by timdorr** [comment]
Yes, it's one of the option_codes on the vehicle: http://options.teslastuff.net/

**Comment by FrancoSabadini** [comment]
Thanks for the quick response @timdorr, can you give me a bit more info on that please? E.g., how can I automate getting the battery size using the option codes? Will the API always return multiple option codes for each car? (I still haven't tried this in a real car as I'm in the research stage and don't have yet access to a Tesla car to try this).

**Comment by timdorr** [comment]
Look through the cassette file from the test suite: https://github.com/timdorr/model-s-api/blob/master/spec/cassettes/client-vehicles.yml

That info is on the vehicles endpoint, so you can get it without pinging the car. It's how the app determines what to show on screen, such as the color, rims, and roof.
