### ISSUE TITLE
ID/Secret seems to have expired

### ISSUE THREAD

**Issue by therippa** [timdorr/model-s-api#60]
The ID/Secret used to talk to the Tesla servers seems to have expired.  Can you generate a new one (or post how to generate a new one)?

**Comment by ChadMoran** [comment]
Could you specify how you came to believe they expired?

I just confirmed they are active and even the current version of the Tesla app is using them.

**Comment by timdorr** [comment]
Yep, I used the same ones this morning. If they need to be refreshed, just pull the latest apk/ipa and grep through the files for it. It's not hard to find (especially since they moved to React Native...)
