### ISSUE TITLE
Recent api updates

### ISSUE THREAD

**Issue by jonasman** [timdorr/model-s-api#62]
Hi, i dont know if you notice but the API has been updated recently with lots of changes.

I updated my swift library already here's some changes i found out:

https://github.com/jonasman/TeslaSwift/commit/7ee7a0fa36a4015124873f0a52309d8cde9cef7b
https://github.com/jonasman/TeslaSwift/commit/b3f2641a5956758d74a17cc1db441fd4392dad02
https://github.com/jonasman/TeslaSwift/commit/09fcbdfb37f8957af834de66308b0233c39a07b4
https://github.com/jonasman/TeslaSwift/commit/bc95dabf42558b6f833dc28a8d0b5b712bf13a34

**Comment by ameyakhare** [comment]
Have the endpoints to everything in /vehicles/{vehicle_id}/... been changed as well? I can use the oauth/token endpoint and vehicles/ endpoint, but everything with the {vehicle_id} url parameter returns 404 (this includes /data_request & /charge_state). Does anyone know the issue?

**Comment by timdorr** [comment]
Use the id vs the vehicle_id.

**Comment by timdorr** [comment]
For this kind of stuff, a PR is better. I've been (extremely) slowly building out a docs site here. Hopefully, I can get that done soon and we can have more of these fixtures in place and return values documented.

**Comment by jonasman** [comment]
I just wanted to document the changes in an issue.
Prs could be open linked to this issue
