### ISSUE TITLE
Update for new endpoints

### ISSUE THREAD

**Issue by timdorr** [timdorr/model-s-api#7]
Tesla has moved quite a bit around on the API with the release of 6.0 and the latest apps. There are a couple new endpoints and most have been moved around.

The server has switched to `owner-api.teslamotors.com` and there is certificate pinning in the apps, making sniffing via proxy more difficult. I may try poking around with [APK Studio](http://apkstudio.codeplex.com/) to see if I can remove the pin or have it trust a different cert. 

### Changes

- [x] Update server to `owner-api.teslamotors.com`
- [x] New `/command/` endpoints
  - [x] `charge_max_range`
  - [x] `charge_standard`
  - [x] `sun_roof_control`
  - [x] `flash_lights`
  - [x] `honk_horn`
  - [x] `door_lock`
  - [x] `charge_port_door_open`
  - [x] `trunk_open`
  - [x] `remote_start_drive`
  - [ ] `upcoming_calendar_entries`
  - [x] `set_temps`
  - [x] `charge_start`
  - [x] `auto_conditioning_start`
  - [x] `charge_stop`
  - [x] `auto_conditioning_stop`
  - [x] `door_unlock`
- [x] New `/data_request/` endpoints
  - [x] `charge_state`  
  - [x] `climate_state` 
  - [x] `drive_state`   
  - [x] `gui_settings`  
  - [x] `vehicle_state` 
- [x] Misc vehicle endpoints
  - [x] `wake_up`
  - [x] `mobile_enabled`
- [ ] `notification_preferences`
- [ ] `vehicle_subscriptions`

**Comment by Tkizzy** [comment]
Hi - also 

https://owner-api.teslamotors.com/api/1/vehicles gives a list of vehicles on the acount as far as I can tell. Empty if there are none yet.

What is the full URL of the vehicle_subscriptions endpoint and what does it do?
