### ISSUE TITLE
New speed limit API

### ISSUE THREAD

**Issue by jonasman** [timdorr/model-s-api#71]
just creating the issue if anyone finds out the API

**Comment by scottrobertson** [comment]
It's been added to the Tasker plugin, so they must have found it. Will ping them and ask them to add it to the docs.

**Comment by jonahwh** [comment]
Hi @scottrobertson, I'm the dev of the Tasker plugin - I don't think I've received any contact from you, but I'll make a PR here!

**Comment by scottrobertson** [comment]
Hey @jonahwh. I can't even remember which channel I sent it via now... But you are here now so it's all good :D
