### ISSUE TITLE
wake_up

### ISSUE THREAD

**Issue by jonasman** [timdorr/model-s-api#72]
Anyone knows what does a `wake_up` command do? saw it here:
https://github.com/gglockner/teslajson/blob/master/teslajson.py#L142

**Comment by timdorr** [comment]
It wakes up the car from a deep sleep state to be able to respond to various API commands or get certain state only available when it's online. The commands will do this automatically, but this can be done to "pre-warm" the car out of sleep so subsequent commands will be faster.
