### ISSUE TITLE
Update for oAuth flow

### ISSUE THREAD

**Issue by timdorr** [timdorr/model-s-api#8]
Some time around the release of the 6.0 firmware, Tesla switched to a more sane oAuth-based API (good move! :+1:). 

I assume posting the raw oAuth tokens is a no-no, so either instructions need to be provided on how to get them or we leave that as an exercise for the reader. Either way, the project is busted without it.

- [x] oAuth Login
- [x] Bearer token auth
- [x] How to find the oAuth token/secret (or not?)

**Comment by Tkizzy** [comment]
I'm still struggling to get the client_id and client_secret. Any help would be greatly appreciated.

I tried using charles proxy with an ssl certificate installed on an iPhone, but it says remote host closed connection during handshake.

**Comment by Diolor** [comment]
@Tkizzy you won't have any chance with Charles as it's SSL encrypted endpoints. 

I was able to get the Api client/secret + successfully get a Access token and make an auth-ed request. E.g. `api/1/vehicles`. I would not wish however to post them here in order to protect the company.
