### ISSUE TITLE
Open a website through API on Tesla screen

### ISSUE THREAD

**Issue by radokristof** [timdorr/model-s-api#81]
Dear Tesla Owners!

We want to develop an app which has Tesla support and we want to periodically display something on the screen (best would be if we can display a website). Can this be achieved somehow? It won't be a problem if it is not possible with this API, but somehow through another way (programatically). 
I don't own a Tesla so I don't fully know what are the other possibilities, please let me know if you know any.

Thanks

**Comment by timdorr** [comment]
Nope, this isn't possible with the API. You would need to bring up the browser in the car manually.
